ydb-platform/yoj-project

repository-inmemory/src/main/java/tech/ydb/yoj/repository/test/inmemory/InMemoryRepositoryTransaction.java
repository-inmemory/src/main/java/tech/ydb/yoj/repository/test/inmemory/legacy/LegacyInMemoryRepositoryTransaction.java
repository-inmemory/src/main/java/tech/ydb/yoj/repository/test/inmemory/legacy/NormalExecutionWatcher.java
repository-ydb-v1/src/main/java/tech/ydb/yoj/repository/ydb/YdbRepositoryTransaction.java
repository-ydb-v1/src/test/java/tech/ydb/yoj/repository/ydb/YdbRepositoryIntegrationTest.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/YdbRepositoryTransaction.java
repository-ydb-v2/src/test/java/tech/ydb/yoj/repository/ydb/YdbRepositoryIntegrationTest.java

commit on rollback - it's legacy for pre-mvcc era. Now it's no longer needed

No commit on rollback

---

pom.xml
repository-ydb-v1/pom.xml
repository-ydb-v1/src/test/resources/log4j2.yaml
repository-ydb-v2/pom.xml
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/YdbRepositoryTransaction.java
repository-ydb-v2/src/test/resources/log4j2.yaml
repository/src/main/java/tech/ydb/yoj/repository/db/readtable/ReadTableParams.java

Now we use:
* YDB Java SDK 2.1.7 -> 2.1.10 + new ReadTable settings
* New YDB protobuf artifacts: 1.6.0
* gRPC 1.51.3->1.59.1
* protobuf 3.21.7->3.24.0
* (test) Jackson 2.14.1->2.16.1
* (test) AssertJ 3.22.0->3.25.1
Did not update (vulnerable) snakeyaml 1.33, because it is *ONLY* used in YOJ tests.

Update YOJ dependencies. Remove unneeded test dependency on restito

---

bom/pom.xml
databind/pom.xml
databind/src/main/java/tech/ydb/yoj/databind/schema/reflect/KotlinDataClassComponent.java
databind/src/main/java/tech/ydb/yoj/databind/schema/reflect/KotlinDataClassType.java
databind/src/main/java/tech/ydb/yoj/databind/schema/reflect/KotlinDataClassTypeFactory.java
databind/src/main/java/tech/ydb/yoj/databind/schema/reflect/KotlinReflectionDetector.java
databind/src/main/java/tech/ydb/yoj/databind/schema/reflect/PojoType.java
databind/src/main/java/tech/ydb/yoj/databind/schema/reflect/StdReflector.java
databind/src/test/kotlin/tech/ydb/yoj/databind/schema/KotlinJvmRecordSchemaTest.kt
databind/src/test/kotlin/tech/ydb/yoj/databind/schema/KotlinSchemaTest.kt
databind/src/test/resources/log4j2.yaml
pom.xml
repository-inmemory/pom.xml
repository-test/pom.xml
repository-ydb-common/pom.xml
repository-ydb-v1/pom.xml
repository-ydb-v2/pom.xml
repository/pom.xml
util/pom.xml

Kotlin support is enabled by default if you have `kotlin-stdlib` *AND* `kotlin-reflection` 1.9.x on your classpath.
Note that you can use Kotlin data classes exposed as Java records (`@JvmRecord`) even if you have *NO* Kotlin dependencies on your classpath.
Fixes: #7

#7: Support Kotlin data classes in StdReflector

---

repository-ydb-v1/src/main/java/tech/ydb/yoj/repository/ydb/YdbRepositoryTransaction.java
repository-ydb-v1/src/main/java/tech/ydb/yoj/repository/ydb/table/YdbTable.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/YdbRepositoryTransaction.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/table/YdbTable.java

Users want to execute scan query on stream. At the moment, they want to execute custom queries, so changes to the Table can be made a little later. It seems to me that this will be the main case for scan query

Stream scan query support

---

databind/src/main/java/tech/ydb/yoj/databind/schema/reflect/KotlinDataClassComponent.java
databind/src/test/kotlin/tech/ydb/yoj/databind/schema/KotlinSchemaTest.kt

YOJ accepts private constructors and uses private fields for POJOs. Do the same for private Kotlin `data class` properties (call `setAccessible()`).

Support private properties in Kotlin data classes

---

databind/src/main/java/tech/ydb/yoj/databind/ByteArray.java
databind/src/main/java/tech/ydb/yoj/databind/FieldValueType.java
databind/src/main/java/tech/ydb/yoj/databind/expression/FieldValue.java
databind/src/main/java/tech/ydb/yoj/databind/expression/IllegalExpressionException.java
databind/src/main/java/tech/ydb/yoj/databind/expression/ModelField.java
databind/src/test/java/tech/ydb/yoj/databind/ByteArrayTest.java
repository-inmemory/src/main/java/tech/ydb/yoj/repository/test/inmemory/Columns.java
repository-test/src/main/java/tech/ydb/yoj/repository/test/RepositoryTest.java
repository-test/src/main/java/tech/ydb/yoj/repository/test/entity/TestEntities.java
repository-test/src/main/java/tech/ydb/yoj/repository/test/sample/TestEntityOperations.java
repository-test/src/main/java/tech/ydb/yoj/repository/test/sample/model/BytePkEntity.java
repository-ydb-v1/src/main/java/tech/ydb/yoj/repository/ydb/yql/YqlPrimitiveType.java
repository-ydb-v1/src/test/java/tech/ydb/yoj/repository/ydb/TestYdbRepository.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/yql/YqlPrimitiveType.java
repository/src/main/java/tech/ydb/yoj/repository/db/EntityIdSchema.java

Byte arrays in primary keys support.
We can't do it with simple byte[], because records default comparator and equals uses compare adresses, not real data. Special class for this looks better, than magic over byte[]

ByteArray class for primary keys with byte[]

---

repository-ydb-v1/src/main/java/tech/ydb/yoj/repository/ydb/YdbRepositoryTransaction.java
repository-ydb-v1/src/main/java/tech/ydb/yoj/repository/ydb/YdbSpliterator.java
repository-ydb-v1/src/test/java/tech/ydb/yoj/repository/ydb/YdbSpliteratorTest.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/YdbRepositoryTransaction.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/YdbSpliterator.java
repository-ydb-v2/src/test/java/tech/ydb/yoj/repository/ydb/YdbSpliteratorTest.java

* use record instead of lombok.Value in internal YdbSpliterator object
* save and close spliterators instead of streams.

Spliterator refactoring

---

repository-ydb-v1/src/main/java/tech/ydb/yoj/repository/ydb/YdbSpliterator.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/YdbSpliterator.java

Previously, we not colose the sliterator, but the Stream, which caused the test that checks what cannot be read from a closed stream to break.

spliterator-bugfix: Spliterator fix

---

.bazelproject
databind/BUILD
databind/pom.xml
databind/src/main/java/tech/ydb/yoj/databind/CustomValueType.java
databind/src/main/java/tech/ydb/yoj/databind/CustomValueTypes.java
databind/src/main/java/tech/ydb/yoj/databind/converter/StringColumn.java
databind/src/main/java/tech/ydb/yoj/databind/converter/StringValueType.java
databind/src/main/java/tech/ydb/yoj/databind/schema/Column.java
databind/src/main/java/tech/ydb/yoj/databind/schema/reflect/KotlinDataClassComponent.java
databind/src/main/java/tech/ydb/yoj/databind/schema/reflect/PojoField.java
databind/src/main/java/tech/ydb/yoj/databind/schema/reflect/RecordField.java
repository-inmemory/src/test/java/tech/ydb/yoj/repository/test/inmemory/TestInMemoryRepository.java
repository-test/src/main/java/tech/ydb/yoj/repository/test/RepositoryTest.java
repository-test/src/main/java/tech/ydb/yoj/repository/test/entity/TestEntities.java
repository-test/src/main/java/tech/ydb/yoj/repository/test/sample/TestEntityOperations.java
repository-test/src/main/java/tech/ydb/yoj/repository/test/sample/model/VersionColumn.java
repository-test/src/main/java/tech/ydb/yoj/repository/test/sample/model/VersionedAliasedEntity.java
repository-test/src/main/java/tech/ydb/yoj/repository/test/sample/model/annotations/Digest.java
repository-test/src/main/java/tech/ydb/yoj/repository/test/sample/model/annotations/Sha256.java
repository-test/src/main/java/tech/ydb/yoj/repository/test/sample/model/annotations/YojString.java
repository-ydb-v1/src/test/java/tech/ydb/yoj/repository/ydb/TestYdbRepository.java
repository-ydb-v2/src/test/java/tech/ydb/yoj/repository/ydb/TestYdbRepository.java
util/src/main/java/tech/ydb/yoj/util/lang/Annotations.java

Review comments fixed:
- simple test;
- Annotations.java moved to util module;
- comment about search added.

Meta-Annotations for @Column and @CustomValueType

---

repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/LazyGrpcTransport.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/YdbRepository.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/client/SessionManager.java
repository-ydb-v2/src/test/java/tech/ydb/yoj/repository/ydb/YdbRepositoryIntegrationTest.java
util/src/main/java/tech/ydb/yoj/util/function/MoreSuppliers.java

This way we don't initialize the GRPC transport and session manager before we need them.

#58: `repository-ydb-v2`: Defer initialization of YDB GRPC transport from `YdbRepository` constructor to first usage

---

databind/src/main/java/tech/ydb/yoj/databind/expression/FilterBuilder.java
repository-test/src/main/java/tech/ydb/yoj/repository/test/TableQueryBuilderTest.java

This way, `where(field)` does not replace the whole filter expression with itself, but gracefully adds query conditions instead, e.g.:
```java
return db.computeInstances().query()
.where("id.project").eq(project)
.where("id.name").eq(name)
.limit(10)
.find();
```

#60: FIX: Make `TableQueryBuilder`'s `where(field)` and `and(field)` have equivalent meaning

---

databind/src/main/java/tech/ydb/yoj/databind/FieldValueType.java
databind/src/main/java/tech/ydb/yoj/databind/expression/FieldValue.java
databind/src/main/java/tech/ydb/yoj/databind/expression/IllegalExpressionException.java
databind/src/main/java/tech/ydb/yoj/databind/expression/ModelField.java
repository-inmemory/src/main/java/tech/ydb/yoj/repository/test/inmemory/Columns.java
repository-test/src/main/java/tech/ydb/yoj/repository/test/entity/TestEntities.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/yql/YqlPrimitiveType.java
repository-ydb-v2/src/test/java/tech/ydb/yoj/repository/ydb/yql/YqlTypeAllTypesLegacyMappingTest.java
repository-ydb-v2/src/test/java/tech/ydb/yoj/repository/ydb/yql/YqlTypeAllTypesRecommendedMappingTest.java
repository/src/main/java/tech/ydb/yoj/repository/db/EntityIdSchema.java
repository/src/main/java/tech/ydb/yoj/repository/db/common/CommonConverters.java

Note that this makes backward incompatible method signature changes in `FieldValue.Tuple` (which should **not** have been used in application code, anyway, but...)

#71: Support `java.util.UUID` natively (as `FieldValueType.UUID`)

---

pom.xml
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/client/QueryInterceptingSession.java

Bump YDB SDK to v2.2.2 which has updated Topic API (and discovery enhancements, which YOJ does is not adding support for... at least not right now.)

Update YDB SDK to v2.2.2

---

repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/YdbRepositoryTransaction.java
repository-ydb-v2/src/test/java/tech/ydb/yoj/repository/ydb/YdbRepositoryIntegrationTest.java

**Experimental API:** Add minimal compatibility between new YDB SDK's YdbTransaction and YOJ's YdbRepositoryTransaction, accessible inside transaction body via
```java
Tx tx = Tx.Current.get();
// YOJ tx:
YdbRepositoryTransaction yojTx = (YdbRepositoryTransaction) tx.getRepositoryTransaction();
// YDB SDK tx:
YdbTransaction ydbTx = yojTx.toSdkTransaction();
```
In the compatibility wrapper, the `getStatusFuture()` method always throws `UnsupportedOperationException`, and other methods are fully functional (`getSessionId()` will throw if there is no active YDB session, though.)

#80: Minimal compatibility: Return YDB SDK's YdbTransaction from YOJ's YdbRepositoryTransaction

---

repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/merge/ByEntityYqlQueriesMerger.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/statement/CountAllStatement.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/statement/DeleteAllStatement.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/statement/DeleteByIdStatement.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/statement/FindAllYqlStatement.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/statement/FindInStatement.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/statement/FindRangeStatement.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/statement/FindStatement.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/statement/FindYqlStatement.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/statement/InsertYqlStatement.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/statement/MultipleVarsYqlStatement.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/statement/PredicateStatement.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/statement/UpdateByIdStatement.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/statement/UpdateInStatement.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/statement/UpsertYqlStatement.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/statement/YqlStatement.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/table/YdbTable.java
repository-ydb-v2/src/test/java/tech/ydb/yoj/repository/ydb/YdbRepositoryCacheTest.java
repository-ydb-v2/src/test/java/tech/ydb/yoj/repository/ydb/YdbRepositoryIntegrationTest.java
repository-ydb-v2/src/test/java/tech/ydb/yoj/repository/ydb/merge/QueriesMergerTest.java
repository-ydb-v2/src/test/java/tech/ydb/yoj/repository/ydb/statement/DeleteByIdStatementTest.java
repository-ydb-v2/src/test/java/tech/ydb/yoj/repository/ydb/statement/FindInStatementIntegrationTest.java
repository-ydb-v2/src/test/java/tech/ydb/yoj/repository/ydb/statement/InsertYqlStatementTest.java
repository-ydb-v2/src/test/java/tech/ydb/yoj/repository/ydb/statement/UpsertYqlStatementTest.java
repository/src/main/java/tech/ydb/yoj/repository/db/TableDescriptor.java

There is only one change - I create a TableDescriptor record and pass it to the only one сщтыекгсещк ща YqlStatement, what means that all statements have to get TableDescriptor in their constructor

TableDescriptor in Statements

---

databind/src/main/java/tech/ydb/yoj/databind/schema/Changefeed.java
databind/src/main/java/tech/ydb/yoj/databind/schema/Schema.java
databind/src/test/java/tech/ydb/yoj/databind/schema/ChangefeedSchemaTest.java
repository-test/src/main/java/tech/ydb/yoj/repository/test/sample/model/ChangefeedEntity.java
repository-ydb-v2/BUILD
repository-ydb-v2/pom.xml
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/client/YdbSchemaOperations.java
repository-ydb-v2/src/test/java/tech/ydb/yoj/repository/ydb/YdbRepositoryIntegrationTest.java

In this PR, we are adding an option to specify a list of consumers that will be created alongside the CDC topic during the initial bootstrap of the application.
A minor consideration is that TopicService/AlterTopic is not idempotent and will throw an exception if we specify already existing consumers in the addConsumer block. To address this behavior, we will perform a describe operation each time a table is attempted to be created.
These changes have been tested against local YDB (ydbplatform/local-ydb:latest version).

Support for predefined consumers of CDC topics

---

repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/YdbConfig.java

In PR #121, I made a stupid mistake with the new balancing configuration. Currently, the new options are not available due to incorrect visibility. Fixed in this pull request.

Fix balancing config access

---

databind/src/main/java/tech/ydb/yoj/databind/expression/OrderExpression.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/yql/YqlListingQuery.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/yql/YqlOrderBy.java
repository-ydb-v2/src/test/java/tech/ydb/yoj/repository/ydb/YdbRepositoryIntegrationTest.java
repository/src/main/java/tech/ydb/yoj/repository/db/EntityExpressions.java
repository/src/main/java/tech/ydb/yoj/repository/db/TableQueryBuilder.java
repository/src/main/java/tech/ydb/yoj/repository/db/list/InMemoryQueries.java

Add experimental `unordered()` API to all common query paths 
(`OrderExpression`+`EntityExpressions`, `TableQueryBuilder`, `YqlOrderBy`).
The experimental API sets *no particular sort order* for the query results.
That is, the results will be returned in *an implementation-defined order*
which is subject to change at any time, *potentially even giving a different
ordering for repeated executions of the same query*.
This is different from the `OrderExpression` being `null` or `YqlOrderBy` missing,
because YOJ interprets these as "order query results by entity ID ascending" 
to ensure maximum predictability of query results.
There *might be* some modest performance gains from removing an implicit `ORDER BY`
clause from YOJ queries. The new experimental API allows users to take advantage
of …

#135: Allow queries with no particular sort order

---

repository-inmemory/src/main/java/tech/ydb/yoj/repository/test/inmemory/InMemoryTable.java
repository-test/src/main/java/tech/ydb/yoj/repository/test/sample/model/UniqueProject.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/merge/ByEntityYqlQueriesMerger.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/statement/FindYqlStatement.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/statement/Statement.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/statement/YqlStatement.java
repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/table/YdbTable.java
repository-ydb-v2/src/test/java/tech/ydb/yoj/repository/ydb/YdbRepositoryIntegrationTest.java
repository-ydb-v2/src/test/java/tech/ydb/yoj/repository/ydb/merge/QueriesMergerTest.java
repository/src/main/java/tech/ydb/yoj/repository/db/AbstractDelegatingTable.java
repository/src/main/java/tech/ydb/yoj/repository/db/Table.java
repository/src/main/java/tech/ydb/yoj/repository/db/cache/EmptyFirstLevelCache.java
repository/src/main/java/tech/ydb/yoj/repository/db/cache/EmptyRepositoryCache.java
repository/src/main/java/tech/ydb/yoj/repository/db/cache/FirstLevelCache.java
repository/src/main/java/tech/ydb/yoj/repository/db/cache/FirstLevelCacheImpl.java
repository/src/main/java/tech/ydb/yoj/repository/db/cache/FirstLevelCacheProvider.java
repository/src/main/java/tech/ydb/yoj/repository/db/cache/RepositoryCache.java
repository/src/main/java/tech/ydb/yoj/repository/db/cache/TransactionLocal.java
repository/src/test/java/tech/ydb/yoj/repository/db/cache/FirstLevelCacheTest.java

Using `find([view], ID)`, `save()`, `insert()` on the same entity but with a different table name, will produce surprising results, essentially remembering which table was queried first and returning cached results from the first queried table for the whole transaction.
This PR fixes the underlying caching mechanisms (`FirstLevelCache` and `RepositoryCache`), augmenting their cache keys with `TableDescriptor`. This PR also improves the documentation on both these caches.

#131: FIX: Incorrect query results when same entity but different tables is used with find, save and insert

---

repository-ydb-v2/src/main/java/tech/ydb/yoj/repository/ydb/table/YdbTable.java

Required for execution of custom `Statement`s in descendants without duplication of that fields.

Allow protected access to YdbTable fields

---

repository/src/main/java/tech/ydb/yoj/repository/db/StdTxManager.java
repository/src/main/java/tech/ydb/yoj/repository/db/TxImpl.java
repository/src/main/java/tech/ydb/yoj/repository/db/TxNameGenerator.java
repository/src/test/java/tech/ydb/yoj/repository/db/StdTxManagerTest.java
repository/src/test/java/tech/ydb/yoj/repository/db/testcaller/TestDbTxCaller.java
repository/src/test/java/tech/ydb/yoj/repository/testcaller/TestTxCaller.java
util/src/main/java/tech/ydb/yoj/util/lang/CallStack.java

...introducing `TxNameGenerator.LONG` (for longer but more human-readable default tx names)
and `TxNameGenerator.NONE` (for forcing everyone to call `TxManager.withName(...)`)

noticket: Customize default transaction name generation in `StdTxManager`
